name: Test
on:
  push:
    branches:
      - 2.x
  pull_request:
    branches:
      - 2.x

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    env:
      PRIVATE_REPO_GITHUB: ${{ secrets.PRIVATE_REPO_GITHUB }}
      PRIVATE_USER_TOKEN_GITHUB: ${{ secrets.PRIVATE_USER_TOKEN_GITHUB }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        composer-version:
          - "2"
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Update composer
        run: composer --verbose self-update --${{ matrix.composer-version }}

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: composer --verbose install

      - name: Run tests
        run: composer test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PHP
          fail_ci_if_error: false
          files: ./test/output/clover.xml
          flags: unittests
          name: codecov
          verbose: true
